wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    code_path: code/RL/sac/sac.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1654699413
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 35
      4: 3.8.12
      5: 0.12.16
      8:
      - 5
alpha:
  desc: null
  value: 0.2
automatic_entropy_tuning:
  desc: null
  value: false
batch_size:
  desc: null
  value: 256
beta:
  desc: null
  value: 1.0
beta_monitor:
  desc: null
  value: critic
buffer_size:
  desc: null
  value: 1000000
cuda:
  desc: null
  value: false
device:
  desc: null
  value: cuda
dryrun:
  desc: null
  value: false
env_name:
  desc: null
  value: NutAssemblyDense
eval:
  desc: null
  value: true
eval_freq:
  desc: null
  value: 10
exp_name:
  desc: null
  value: rl
gamma:
  desc: null
  value: 0.99
hidden_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.0003
num_eval_episodes:
  desc: null
  value: 10
num_steps:
  desc: null
  value: 10000000
policy:
  desc: null
  value: Gaussian
seed:
  desc: null
  value: 66
start_steps:
  desc: null
  value: 10000
target_update_interval:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
torch_deterministic:
  desc: null
  value: true
updates_per_step:
  desc: null
  value: 1
